name: myWorkflow

on:
  - pull_request
  - workflow_dispatch

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: mkdir dirForTests
      - run: |
            gradle clean build
            mv build/jacoco/test.exec dirForTests
      - uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: dirForTests/*.exec

  checkstyle:
    name: checkstyle
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run check style
        uses: nikitasavinov/checkstyle-action@master
        with:
          checkstyle_config: 'config/checkstyle/checkstyle.xml'

  coverage:
    name: coverage
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: create dir
        run: mkdir build
      - name: Set up JDK 1.8
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: download tests from artifact
        uses: actions/download-artifact@v3
        with:
          name: my-artifact
          path: build/jacoco/
      - name: Run Coverage
        run: |
          chmod +x gradlew
          ./gradlew jacocoTestReport
      - name: Add coverage to PR
        id: jacoco
        uses: madrapps/jacoco-report@v1.6.1
        with:
          paths: |
            ${{ github.workspace }}/**/build/reports/jacoco/jacocoTestReport.xml
          token: ${{secrets.GITHUB_TOKEN}}
          min-coverage-overall: 40
          min-coverage-changed-files: 60
          title: Code Coverage
          update-comment: true
