name: myWorkflow

on:
  - pull_request
  - workflow_dispatch

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: gradle clean build

  checkstyle:
    name: checkstyle
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run check style
        uses: nikitasavinov/checkstyle-action@master
        with:
          checkstyle_config: 'config/checkstyle/checkstyle.xml'

  coverage:
    name: coverage
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Run Coverage
        run: |
          chmod +x gradlew
          ./gradlew test jacocoTestReport
      - name: Add coverage to PR
        id: jacoco
        uses: madrapps/jacoco-report@v1.6.1
        with:
          paths: |
            ${{ github.workspace }}/**/build/reports/jacoco/prodNormalDebugCoverage/prodNormalDebugCoverage.xml,
            ${{ github.workspace }}/**/build/reports/jacoco/**/debugCoverage.xml
          token: ${{secrets.GITHUB_TOKEN}}
          min-coverage-overall: 40
          min-coverage-changed-files: 60
